image:
  file: .gitpod.Dockerfile

tasks:
  - init: mkdir ../go ../go/bin && make deps && curl -s "https://raw.githubusercontent.com/JesterOrNot/gosh/master/build" | sh
    command: make test && gosh
