image:
  file: .gitpod.Dockerfile

tasks:
  - init: mkdir ../go ../go/bin && pip3 install -r requirements.txt && make deps && curl -s "https://raw.githubusercontent.com/JesterOrNot/gosh/master/build" | sh
    command: make test && gosh